KuraProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('', views.index, name='index'),
    path('bio', views.bio, name='bio'),
    path('confirmation/<str:registration_number>/', views.confirmation, name='confirmation'),
    path('success', views.success, name='success'),
    path('success_vote', views.success_vote, name='success_vote'),
    path('dashboard', views.voter_list, name='dashboard'),
    path('voter_list', views.voter_list, name='voter_list'),
    path('create_voter', views.create_voter, name='create_voter'),
    path('create_election', views.create_election, name='create_election'),
    path('election_list', views.election_list, name='election_list'),
    path('candidate_list', views.candidate_list, name='candidate_list'),
    path('create_candidate', views.create_candidate, name='create_candidate'),
    path('cast_vote/<str:election_id>/', views.cast_vote, name='cast_vote'),
    path('cast_vote_auth', views.cast_vote_auth, name='cast_vote_auth'),
    path('check_details_auth', views.check_details_auth, name='check_details_auth'),
    path('update_details_auth', views.update_details_auth, name='update_details_auth'),
    path('voter_details/<str:registration_number>/', views.voter_details, name='voter_details'),
    path('update_details/<str:registration_number>/', views.update_details, name='update_details'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('user_account', views.user_account, name='user_account'),
    path('admin_account', views.admin_account, name='admin_account'),
    path('log_out', views.log_out, name='log_out'),
    path('admin_log_out', views.admin_log_out, name='admin_log_out'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('activation_failed', views.activation_failed, name='activation_failed')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from datetime import datetime, timezone
from django.contrib.auth.models import User
from django.db import models

class Election(models.Model):
    election_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self):
        return self.election_name

class Candidate(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=10, default=None)
    email = models.EmailField(default="test@test.com")
    first_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    votes = models.IntegerField(default=0)

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)

    def __str__(self):
        return self.first_name

class Voter(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=10, default=None)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=None)
    email = models.EmailField(default="test@test.com")
    first_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    status = models.BooleanField(default=False)

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)

    def __str__(self):
        return self.first_name

vote/forms.py
from django import forms
from .models import Voter, County, Constituency, Ward


class VoterForm(forms.ModelForm):
    class Meta(object):
        model = Voter
        fields = '__all__'


class CountyForm(forms.ModelForm):
    class Meta(object):
        model = County
        fields = '__all__'

vote/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from vote.models import Candidate, Election, Voter
from KuraProject import settings
from vote.tokens import generate_token


def index(request):
    if request.user.is_authenticated and request.user.is_active:
        fname = request.user.first_name
        context = {
            'fname': fname
        }
    else:
        fname = ''
        context = {
            'fname': fname
        }
    return render(request, 'vote/user/index.html', context)


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!!")
            return redirect('vote:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists!!")
            return redirect('vote:signup')

        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('vote:signup')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.is_active = True

        myuser.save()

        messages.success(request, "Your Account has been created successfully. \n ")

        return redirect('vote:login')

    return render(request, 'vote/auth/signup.html')


def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            return redirect('vote:dashboard')

        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('vote:admin_login')

    return render(request, 'vote/auth/login_admin.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Login Successful.")
            return redirect('vote:index')

        else:
            messages.error(request, "Username or Password is incorrect")

    return render(request, 'vote/auth/login.html')


def admin_log_out(request):
    logout(request)
    return render(request, 'vote/admin/admin_logout.html')


def log_out(request):
    logout(request)
    return render(request, 'vote/auth/logout.html')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        return redirect('vote:login')
    else:
        return render(request, 'vote/auth/activation_failed.html')


def activation_failed(request):
    return render(request, 'vote/auth/activation_failed.html')


def dashboard(request):
    if request.user.is_authenticated and request.user.is_staff:
        total = Voter.objects.count()
        threshold = (total / 10) * 100
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'total': total,
            'threshold': threshold
        }
    else:
        messages.info(request, "Admin privileges required")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/dashboard.html', context)


@login_required
def user_account(request):
    uname = request.user.username
    fname = request.user.first_name
    lname = request.user.last_name
    email = request.user.email

    context = {
        'uname': uname,
        'fname': fname,
        'lname': lname,
        'email': email
    }

    return render(request, 'vote/user/user_account.html', context)


def admin_account(request):
    if request.user.is_authenticated and request.user.is_staff:
        uname = request.user.username
        fname = request.user.first_name
        lname = request.user.last_name
        email = request.user.email
        context = {
            'uname': uname,
            'fname': fname,
            'lname': lname,
            'email': email
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/admin_account.html', context)


@login_required
def bio(request):
    elections = Election.objects.all()
    fname = request.user.first_name
    if Voter.objects.filter(user=request.user.id):
        messages.error(request, "You are already registered as a voter!!")
        return redirect('vote:index')

    if request.method == "POST":
        registration_number = request.POST['registration_number']
        user = request.user
        election_id = request.POST['election']
        first_name = request.POST['first_name']
        surname = request.POST['surname']
        phone_number = request.POST['phone_number']
        gender = request.POST['gender']
        email = request.user.email

        try:
            election = Election.objects.get(id=election_id)
        except Election.DoesNotExist:
            messages.error(request, "Selected election does not exist.")
            return redirect('vote:bio')

        myvoter = Voter.objects.create( registration_number=registration_number, user=user, election=election, email=email,
                                        first_name=first_name, surname=surname,phone_number=phone_number, gender=gender)

        myvoter.save()
        
        return redirect('vote:confirmation', registration_number)
    
    context = {
        'elections': elections,
        'fname': fname
    }

    return render(request, 'vote/user/bio.html', context)


@login_required
def confirmation(request, registration_number):
    elections = Election.objects.all()
    fname = request.user.first_name
    voter = Voter.objects.get(registration_number=registration_number)
    context = {
        'fname': fname,
        'voter': voter,
        'elections': elections
    }
    if request.method == "POST":
        registration_number = request.POST['registration_number']
        user = request.user
        election_id = request.POST['election']
        first_name = request.POST['first_name']
        surname = request.POST['surname']
        phone_number = request.POST['phone_number']
        gender = voter.gender
        email = request.user.email

        try:
            election = Election.objects.get(id=election_id)
        except Election.DoesNotExist:
            messages.error(request, "Selected election does not exist.")
            return redirect('vote:bio')

        my_voter = Voter(registration_number=registration_number, user=user, election=election, first_name=first_name,
                         surname=surname, email=email, phone_number=phone_number, gender=gender)

        my_voter.save()

        return redirect('vote:success')
        
    return render(request, 'vote/user/confirmation.html', context)


@login_required
def success(request):
    if request.user.is_authenticated:
        fname = request.user.first_name
        context = {
            'fname': fname
        }

    return render(request, 'vote/user/success.html', context)


@login_required
def success_vote(request):
    if request.user.is_authenticated:
        fname = request.user.first_name
        context = {
            'fname': fname
        }

    return render(request, 'vote/user/success_vote.html', context)


def create_voter(request):
    if request.user.is_authenticated and request.user.is_staff:
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            registration_number = request.POST['registration_number']
            email = request.user.id
            first_name = request.POST['first_name']
            surname = request.POST['surname']
            phone_number = request.POST['phone_number']
            gender = request.POST['gender']

            myvoter = Voter.objects.create(registration_number=registration_number,
                                           email_id=email, first_name=first_name,
                                           surname=surname, phone_number=phone_number,
                                           gender=gender)

            myvoter.save()

            messages.success(request, "Voter added successfully.")

            return redirect('vote:voter_list')
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:login')

templates/vote/admin/admin_account.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Admin Account</title>
{% endblock %}

{% block body_block %}

    <div class="form">
        <p>Admin Account</p>

        <div class="fieldWrapper3">
            <label for="id_ward_code">Username:</label>
            <label for="id_ward_code">{{ uname }}</label>
        </div>

        <div class="fieldWrapper3">
            <label for="id_ward_code">First Name:</label>
            <label for="id_ward_code">{{ fname }}</label>
        </div>

        <div class="fieldWrapper3">
            <label for="id_ward_code">Last Name:</label>
            <label for="id_ward_code">{{ lname }}</label>
        </div>

        <div class="fieldWrapper3">
            <label for="id_ward_code">Email Address:</label>
            <label for="id_ward_code">{{ email }}</label>
        </div>
    </div>

    <div class="button-group">
        <a id="submit2" href={% url 'vote:log_out' %}>LOGOUT</a>
    </div>

{% endblock %}

templates/vote/admin/admin_base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/styles/admin_style.css">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400&family=Lato:ital,wght@0,300;0,400;0,700;1,400&family=Open+Sans:wght@300;400;500&display=swap" rel="stylesheet">
    {% block title_block %}
        <title></title>
    {% endblock %}
</head>
<body>
    <div class="sidebar">
        <div class="logo">
            <img id="logo" src="{% static 'images/logo.svg' %}" alt="logo">
        </div>
        <div class="link_list">
            <a href={% url 'vote:voter_list' %}>
                <img id="icon" src="{% static 'images/vote_icon.svg' %}" alt="icon">Voters
            </a>
            <a href={% url 'vote:create_election' %}>
                <img id="icon" src="{% static 'images/vote_icon.svg' %}" alt="icon">Add Election
            </a>
            <a href={% url 'vote:election_list' %}>
                <img id="icon" src="{% static 'images/vote_icon.svg' %}" alt="icon">Elections
            </a>
            <a href={% url 'vote:create_candidate' %}>
                <img id="icon" src="{% static 'images/vote_icon.svg' %}" alt="icon">Add Candidates
            </a>
            <a href={% url 'vote:candidate_list' %}>
                <img id="icon" src="{% static 'images/vote_icon.svg' %}" alt="icon">Candidates
            </a>
        </div>
    </div>
    <div id="spacer">

    </div>
    <div class="parent">
        <div class="navbar">
            <div></div>
            <div>
                {% if user.is_authenticated %}
                    <a href={% url 'vote:admin_account' %}>Hi, {{ fname }} {{ lname }}</a>
                {% endif %}
            </div>
        </div>

    {% block body_block %}

    </div>

    {% endblock %}

</body>
</html>

templates/vote/admin/admin_login.html
{% extends 'vote/admin/../auth/auth_base.html' %}
{% load static %}
{% block title_block %}
    <title>Login</title>
{% endblock %}
<!DOCTYPE html>
<html lang="en">

{% block body_block %}

    <body>
        <div class="form">
            <form method="post" action="/vote/login">

                {% for message in messages %}
                <div class="message">
                    <h3>Message:</h3> {{ message }}
                </div>
                <br>
                {% endfor %}

                <h1> LOGIN </h1>
                {% csrf_token %}
                <div class="field">
                    <label for="username"> Username </label>
                    <input type="text" id="username" name="username" required>
                </div>

                <div class="field">
                    <label for="pass1"> Password </label>
                    <input type="password" id="pass1" name="pass1" required>
                </div>

                <button type="submit" class="submit"> LOGIN </button>

                <div class="options">
                    <a href="#" >Forgot Password?</a>
                    <a href="{% url 'vote:signup' %}" >Click Here to Signup</a>
                </div>

            </form>
        </div>
    </body>
{% endblock %}

templates/vote/admin/constituency_detail.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Constituency Detail</title>
{% endblock %}

{% block body_block %}

    <form method="post" action="/vote/constituency_detail">
        {% csrf_token %}
        <div class="form">
            <p>Constituency</p>
            <div class="fieldWrapper_group">
                <div class="fieldWrapper2">
                    <label for="id_constituency_code">Constituency Code</label>
                    <input class="input" type="text" name="constituency_code" maxlength="8" id="id_constituency_code" required>
                </div>

                <div class="spacer"></div>

                <div class="fieldWrapper2">
                    <label for="id_constituency_name">Constituency Name</label>
                    <input class="input" type="text" name="constituency_name" maxlength="200" id="id_constituency_name" required>
                </div>
            </div>

            <div class="fieldWrapper_group">
                <div class="short">
                    {{ form.subject.errors }}
                    <label for="county_code">County</label>
                    <select class="input" name="county_code" id="county_code" required>
                        {% for county in county %}
                            <option value={{ county.county_code }}>{{ county.county_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="button-group">
            <input type="reset" class="submit" value="CANCEL CHANGES">
            <input id="submit2" type="submit" value="SUBMIT"/>
        </div>

    </form>

{% endblock %}

templates/vote/admin/county_detail.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Voter Detail</title>
{% endblock %}

{% block body_block %}

    <form method="post" action="/vote/county_detail">
        {% csrf_token %}
        <div class="form">
            <p>County</p>
                <div class="fieldWrapper_group">
                    <div class="fieldWrapper2">
                        <label for="id_county_code">County Code</label>
                        <input class="input" type="text" name="county_code" maxlength="3" id="id_county_code" required>
                    </div>

                    <div class="spacer"></div>

                    <div class="fieldWrapper2">
                        <label for="id_county_name">County Name</label>
                        <input class="input" type="text" name="county_name" maxlength="200" id="id_county_name" required>
                    </div>
                </div>
        </div>

        <div class="button-group">
            <input type="reset" class="submit" value="CANCEL CHANGES">
            <input id="submit2" type="submit" value="SUBMIT"/>
        </div>

    </form>

{% endblock %}

templates/vote/admin/county_list.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Voter List</title>
{% endblock %}

{% block body_block %}

    <table class="table">
        <thead>
            <tr class="table-row">
                <th class="head-item">COUNTY CODE</th>
                <th class="head-item">COUNTY NAME</th>
                <th class="head-item">NO. OF VOTERS</th>
                <th class="head-item"></th>
                <th class="head-item"></th>
            </tr>
        </thead>
        <tbody>
        {% for county in county %}
            <tr class="table-row">
                <td class="cell">{{ county.county_code }}</td>
                <td class="cell">{{ county.county_name }}</td>
                <td class="cell">2500000</td>
                <td class="cell" id="table1"><a class="action2" href="{% url 'vote:update_county' county.county_code %}">Update</a></td>
                <td class="cell" id="table1"><a class="action" href="{% url 'vote:delete_county' county.county_code %}">Delete</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/vote/admin/create_candidate.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Create Candidate</title>
{% endblock %}

{% block body_block %}

    <form action="" method="post">
        <div class="form">
            <p>Create Candidate</p>
            {% csrf_token %}
            <div class="fieldWrapper_group">
                <div class="fieldWrapper2">
                    <label for="registration_number">Registration Number</label>
                    <input class="input" type="text" name="registration_number" maxlength="8" id="registration_number" required>
                </div>

                <div class="spacer"></div>

                <div class="fieldWrapper2">
                    <label for="first_name">First Name</label>
                    <input class="input" type="text" name="first_name" maxlength="254" id="first_name" required="">
                </div>
            </div>

            <div class="fieldWrapper_group">
                <div class="fieldWrapper2">
                    <label for="election">Department</label>
                    <select class="input" name="election" id="election" required>
                        <option>---------SELECT YOUR DEPARTMENT---------</option>
                        {% for election in election_list %}
                            <option value="{{ election.id }}">{{ election.election_name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="spacer"></div>

                <div class="fieldWrapper2">
                    <label for="surname">Last Name</label>
                    <input class="input" type="text" name="surname" maxlength="254" id="surname" required="">
                </div>
            </div>

            <div class="fieldWrapper_group">
                <div class="fieldWrapper2">
                    <label for="phone_number">Phone Number</label>
                    <input class="input" type="text" name="phone_number" maxlength="10" id="phone_number" required="">
                </div>

                <div class="spacer"></div>

                <div class="fieldWrapper2">
                    <label for="gender">Gender</label>
                    <select class="input" name="gender" id="gender" required>
                        <option>---------SELECT GENDER---------</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
            </div>

            <div class="fieldWrapper_group">
                <div class="short">
                    <label for="email">Email Address</label>
                    <input type="text" name="email" maxlength="254" id="email" required>
                </div>
            </div>
        </div>

        <div class="button-group">
            <input class="submit" type="reset" value="CANCEL CHANGES">
            <input id="submit2" type="submit" value="SUBMIT"/>
        </div>
    </form>

{% endblock %}

templates/vote/admin/create_election.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Create Election</title>
{% endblock %}

{% block body_block %}

    <form action="" method="post">
        <div class="form">
            <p>Create Election</p>
            {% csrf_token %}
            <div class="fieldWrapper_group">
                <div class="fieldWrapper2">
                    <label for="election_name">Election Name</label>
                    <input class="input" type="text" name="election_name" maxlength="254" id="election_name" required>
                </div>
            </div>
        </div>

        <div class="button-group">
            <input class="submit" type="reset" value="CANCEL CHANGES">
            <input id="submit2" type="submit" value="SUBMIT"/>
        </div>
    </form>

{% endblock %}

templates/vote/admin/dashboard.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Dashboard</title>
{% endblock %}

{% block body_block %}
    <div class="tab-parent">
        <div class="tab-group">
            <div class="tab">
                <span>{{ total }}</span>
                Registered Voters
            </div>

            <div class="tab">
                <span>10</span>
                Targeted Voters
            </div>

            <div class="tab">
                <span>{{ threshold }} %</span>
                Threshold
            </div>
        </div>

        <div class="tab-group">
            <div class="tab">
                <span>256</span>
                Days to Election
            </div>

            <div class="tab">
                <span>0</span>
                Voters registered today
            </div>

            <div class="tab">
                <span>2</span>
                Voters registered this month
            </div>
        </div>

        <div class="tab-group">
            <div class="tab">
                <span>24</span>
                Most voters in one county
            </div>

            <div class="tab-large">
                <span>Nairobi</span>
                County with the most registered voters
            </div>
        </div>
    </div>
{% endblock %}

templates/vote/admin/delete_constituency.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Delete Constituency</title>
{% endblock %}

{% block body_block %}

    <form method="post">
        {% csrf_token %}
        <div class="form">
            <p>Delete Constituency</p>
                <div class="fieldWrapper_group">
                    <div class="fieldWrapper2">
                        <label for="county_code">Are you sure about this action?</label>
                        <label for="county_code">Action:</label>
                        <label for="county_code">Delete {{ constituency.constituency_name }}</label>
                    </div>
                </div>
        </div>

        <div class="button-group">
            <a type="reset" class="submit" href="{% url 'vote:constituency_list' %}"> BACK </a>
            <input id="submit2" type="submit" value="YES"/>
        </div>

    </form>

{% endblock %}

templates/vote/admin/update_constituency.html
{% extends 'vote/admin/admin_base.html' %}
{% load static %}
{% block title_block %}
    <title>Update Constituency</title>
{% endblock %}

{% block body_block %}

    <form method="post">
        {% csrf_token %}
        <div class="form">
            <p>Constituency</p>
                <div class="fieldWrapper_group">
                    <div class="fieldWrapper2">
                        <label for="constituency_code">Constituency Code</label>
                        <input class="input" type="text" name="constituency_code" maxlength="8" id="constituency_code" readonly value="{{ constituency.constituency_code }}">
                    </div>

                    <div class="spacer"></div>

                    <div class="fieldWrapper2">
                        <label for="constituency_name">Constituency Name</label>
                        <input class="input" type="text" name="constituency_name" maxlength="200" id="constituency_name" required value="{{ constituency.constituency_name }}">
                    </div>
                </div>
                <div>
                    <div class="short">
                        <label for="county_code">County</label>
                        <select class="input" name="county_code" id="county_code" required>
                        {% for list_of_counties in list_of_counties %}
                            <option value={{ list_of_counties.county_code }}>{{ list_of_counties.county_name }}</option>
                        {% endfor %}
                    </select>

                    </div>

                    <div>
                        <span>Current value: {{ constituency.county_code.county_name }}</span>
                    </div>

                </div>
        </div>

        <div class="button-group">
            <input type="reset" class="submit" value="CANCEL CHANGES">
            <input id="submit2" type="submit" value="SUBMIT"/>
        </div>

    </form>

{% endblock %}