KuraProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('', views.index, name='index'),
    path('bio', views.bio, name='bio'),
    path('confirmation/<str:registration_number>/', views.confirmation, name='confirmation'),
    path('success', views.success, name='success'),
    path('success_vote', views.success_vote, name='success_vote'),
    path('dashboard', views.voter_list, name='dashboard'),
    path('voter_list', views.voter_list, name='voter_list'),
    path('create_voter', views.create_voter, name='create_voter'),
    path('create_election', views.create_election, name='create_election'),
    path('election_list', views.election_list, name='election_list'),
    path('candidate_list', views.candidate_list, name='candidate_list'),
    path('create_candidate', views.create_candidate, name='create_candidate'),
    path('cast_vote/<str:election_id>/', views.cast_vote, name='cast_vote'),
    path('cast_vote_auth', views.cast_vote_auth, name='cast_vote_auth'),
    path('check_details_auth', views.check_details_auth, name='check_details_auth'),
    path('update_details_auth', views.update_details_auth, name='update_details_auth'),
    path('voter_details/<str:registration_number>/', views.voter_details, name='voter_details'),
    path('update_details/<str:registration_number>/', views.update_details, name='update_details'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('user_account', views.user_account, name='user_account'),
    path('admin_account', views.admin_account, name='admin_account'),
    path('log_out', views.log_out, name='log_out'),
    path('admin_log_out', views.admin_log_out, name='admin_log_out'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('activation_failed', views.activation_failed, name='activation_failed')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from datetime import datetime, timezone
from django.contrib.auth.models import User
from django.db import models

class Election(models.Model):
    election_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self):
        return self.election_name

class Candidate(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=10, default=None)
    email = models.EmailField(default="test@test.com")
    first_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    votes = models.IntegerField(default=0)

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)

    def __str__(self):
        return self.first_name

class Voter(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    registration_number = models.CharField(max_length=10, default=None)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=None)
    email = models.EmailField(default="test@test.com")
    first_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    status = models.BooleanField(default=False)

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)

    def __str__(self):
        return self.first_name

vote/forms.py
from django import forms
from .models import Voter, County, Constituency, Ward


class VoterForm(forms.ModelForm):
    class Meta(object):
        model = Voter
        fields = '__all__'


class CountyForm(forms.ModelForm):
    class Meta(object):
        model = County
        fields = '__all__'

vote/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from vote.models import Candidate, Election, Voter
from KuraProject import settings
from vote.tokens import generate_token


def index(request):
    if request.user.is_authenticated and request.user.is_active:
        fname = request.user.first_name
        context = {
            'fname': fname
        }
    else:
        fname = ''
        context = {
            'fname': fname
        }
    return render(request, 'vote/user/index.html', context)


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!!")
            return redirect('vote:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists!!")
            return redirect('vote:signup')

        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('vote:signup')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.is_active = True

        myuser.save()

        messages.success(request, "Your Account has been created successfully. \n ")

        return redirect('vote:login')

    return render(request, 'vote/auth/signup.html')


def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            return redirect('vote:dashboard')

        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('vote:admin_login')

    return render(request, 'vote/auth/login_admin.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Login Successful.")
            return redirect('vote:index')

        else:
            messages.error(request, "Username or Password is incorrect")

    return render(request, 'vote/auth/login.html')


def admin_log_out(request):
    logout(request)
    return render(request, 'vote/admin/admin_logout.html')


def log_out(request):
    logout(request)
    return render(request, 'vote/auth/logout.html')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        return redirect('vote:login')
    else:
        return render(request, 'vote/auth/activation_failed.html')


def activation_failed(request):
    return render(request, 'vote/auth/activation_failed.html')


def dashboard(request):
    if request.user.is_authenticated and request.user.is_staff:
        total = Voter.objects.count()
        threshold = (total / 10) * 100
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'total': total,
            'threshold': threshold
        }
    else:
        messages.info(request, "Admin privileges required")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/dashboard.html', context)


@login_required
def user_account(request):
    uname = request.user.username
    fname = request.user.first_name
    lname = request.user.last_name
    email = request.user.email

    context = {
        'uname': uname,
        'fname': fname,
        'lname': lname,
        'email': email
    }

    return render(request, 'vote/user/user_account.html', context)


def admin_account(request):
    if request.user.is_authenticated and request.user.is_staff:
        uname = request.user.username
        fname = request.user.first_name
        lname = request.user.last_name
        email = request.user.email
        context = {
            'uname': uname,
            'fname': fname,
            'lname': lname,
            'email': email
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/admin_account.html', context)


@login_required
def bio(request):
    elections = Election.objects.all()
    fname = request.user.first_name
    if Voter.objects.filter(user=request.user.id):
        messages.error(request, "You are already registered as a voter!!")
        return redirect('vote:index')

    if request.method == "POST":
        registration_number = request.POST['registration_number']
        user = request.user
        election_id = request.POST['election']
        first_name = request.POST['first_name']
        surname = request.POST['surname']
        phone_number = request.POST['phone_number']
        gender = request.POST['gender']
        email = request.user.email

        try:
            election = Election.objects.get(id=election_id)
        except Election.DoesNotExist:
            messages.error(request, "Selected election does not exist.")
            return redirect('vote:bio')

        myvoter = Voter.objects.create( registration_number=registration_number, user=user, election=election, email=email,
                                        first_name=first_name, surname=surname,phone_number=phone_number, gender=gender)

        myvoter.save()
        
        return redirect('vote:confirmation', registration_number)
    
    context = {
        'elections': elections,
        'fname': fname
    }

    return render(request, 'vote/user/bio.html', context)


@login_required
def confirmation(request, registration_number):
    elections = Election.objects.all()
    fname = request.user.first_name
    voter = Voter.objects.get(registration_number=registration_number)
    context = {
        'fname': fname,
        'voter': voter,
        'elections': elections
    }
    if request.method == "POST":
        registration_number = request.POST['registration_number']
        user = request.user
        election_id = request.POST['election']
        first_name = request.POST['first_name']
        surname = request.POST['surname']
        phone_number = request.POST['phone_number']
        gender = voter.gender
        email = request.user.email

        try:
            election = Election.objects.get(id=election_id)
        except Election.DoesNotExist:
            messages.error(request, "Selected election does not exist.")
            return redirect('vote:bio')

        my_voter = Voter(registration_number=registration_number, user=user, election=election, first_name=first_name,
                         surname=surname, email=email, phone_number=phone_number, gender=gender)

        my_voter.save()

        return redirect('vote:success')
        
    return render(request, 'vote/user/confirmation.html', context)


@login_required
def success(request):
    if request.user.is_authenticated:
        fname = request.user.first_name
        context = {
            'fname': fname
        }

    return render(request, 'vote/user/success.html', context)


@login_required
def success_vote(request):
    if request.user.is_authenticated:
        fname = request.user.first_name
        context = {
            'fname': fname
        }

    return render(request, 'vote/user/success_vote.html', context)


def create_voter(request):
    if request.user.is_authenticated and request.user.is_staff:
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            registration_number = request.POST['registration_number']
            email = request.user.id
            first_name = request.POST['first_name']
            surname = request.POST['surname']
            phone_number = request.POST['phone_number']
            gender = request.POST['gender']

            myvoter = Voter.objects.create(registration_number=registration_number,
                                           email_id=email, first_name=first_name,
                                           surname=surname, phone_number=phone_number,
                                           gender=gender)

            myvoter.save()

            messages.success(request, "Voter added successfully.")

            return redirect('vote:voter_list')
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:login')

templates/vote/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png'%}">
    <link rel="stylesheet" type="text/css" href="/static/styles/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400&family=Open+Sans:wght@300;400;500&display=swap" rel="stylesheet">
    {% block title_block %}
    {% endblock %}
</head>

<body>
<div class="parent">
    <div class="navbar">

        <a href="{% url 'vote:index' %}">
            <img class="brand" src="{% static 'images/logo.svg' %}" alt="logo">
        </a>
        <ul>
            <li><a href="/vote">HOME</a> </li>
            <li><a href="#">CONTACT</a> </li>
            <li>
                {% if user.is_authenticated %}
                    <div class="account">
                        <a href={% url 'vote:user_account' %}>Hi, {{ fname }} </a>
                    </div>
                {% else %}
                    <div class="account">
                        <a href={% url 'vote:login' %}>LOGIN</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </div>

    <div class="navbar_small">
        <div>
            <a href="{% url 'vote:index' %}">
                <img class="brand_small" src="{% static 'images/logo.svg' %}" alt="logo">
            </a>
        </div>
        <div>
            <a href="{% url 'vote:user_account' %}">
                <img class="burger" src="{% static 'images/user.svg' %}" alt="logo">
            </a>
        </div>
    </div>

    {% block body_block %}
    {% endblock %}

<div>

{% block footer_block %}
    <div class="footer">
        
        <div class="map">
        </div>
        
        <div class="content-footer">
            <div id="wrapper">
                <div id="header">Services</div>
                <ul id="content">
                    <li><a href={% url 'vote:bio' %}>Voter Registration</a></li>
                    <li><a href={% url 'vote:update_details_auth' %}>Update Registration</a></li>
                    <li><a href={% url 'vote:check_details_auth' %}>Check Registration Status</a></li>
                </ul>
            </div>

            <div id="right-bottom-wrapper">
                <div id="header">Follow Us</div>
                <div id="icons">
                    <div class="first">
                        <img alt="facebook" src="{% static 'images/youtube.svg' %}">
                    </div>
                    <div class="first">
                        <img alt="twitter" src="{% static 'images/facebook.svg' %}">
                    </div>
                    <div class="first">
                        <img alt="instagram" src="{% static 'images/instagram.svg' %}">
                    </div>
                    <div class="last">
                        <img alt="email" src="{% static 'images/twitter.svg' %}">
                    </div>
                </div>
            </div>
        </div>

        <div class="content-footer">
            <div id="wrapper">
                <div id="header">About Us</div>
                <ul id="content">
                    <li><a href="#">Our Vision</a></li>
                    <li><a href="#">Our Mission</a></li>
                    <li><a href="#">Our Leaders</a></li>
                </ul>
            </div>

            <div id="bottom-wrapper">
                <div id="header">
                    <div>
                        Our Newsletter
                    </div>
                </div>
                <form>
                    <input placeholder="johndoe@mail.com">
                    <button class="sub-btn">Subscribe</button>
                </form>
            </div>

        </div>
    </div>
{% endblock %}
</body>
</html>

templates/vote/user/bio.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Voter Registration</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 1 of 2: Voter Registration
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/current.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly fill up the following fields as correctly and accurately as possible.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>
        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="registration_number">Registration Number</label>
                        <input class="input" type="text" name="registration_number" maxlength="9" id="id_serial_number" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="first_name">First Name</label>
                        <input class="input" type="text" name="first_name" maxlength="254" id="first_name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="surname">Surname</label>
                        <input class="input" type="text" name="surname" maxlength="254" id="surname" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="election">Department</label>
                        <select class="input" name="election" id="election" required>
                            <option value="">------SELECT YOUR DEPARTMENT------</option>
                            {% for election in elections %}
                                <option value="{{ election.id }}">{{ election.election_name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        <label for="gender">Gender</label>
                        <select class="input" name="gender" id="gender" required>
                            <option value="">------SELECT YOUR GENDER------</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        <label for="phone_number">Phone Number</label>
                        <input class="input" type="text" name="phone_number" maxlength="10" id="phone_number" required>
                    </div>

                    <div class="button-group">
                        <input type="reset" class="submit" value="CLEAR">
                        <input id="submit2" type="submit" value="NEXT"/>
                    </div>

                </form>
            </div>
        </div>
    </div>
{#<a href={% url 'vote:location' %}>NEXT</a>#}
{#<a id="button5" href="{% url 'vote:location' Voter.email %}">NEXT</a>#}
{% endblock %}

templates/vote/user/cast_vote.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Cast Vote</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title2">
            Cast Your Vote
        </div>

        <div class="content2">
            <div>
                Select your preferred candidate
            </div>
        </div>
        
        <div class="formWrapper">
            <div class="form">
                <form action="{% url 'vote:cast_vote' election.id %}" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <legend><h1>{{ election.election_name }}</h1></legend>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        {% for candidate in election.candidate_set.all %}
                            <input type="radio" name="candidate" id="candidate{{ candidate.id }}" value="{{ candidate.id }}">
                            <label for="candidate{{ candidate.id }}">{{ candidate.first_name }} {{ candidate.surname }}</label><br>
                        {% endfor %}
                    </fieldset>
                    <br>
                    <br>
                    <input class="submit" type="submit" value="Vote">
                </form>
            </div>
        </div>

        <div class="button-parent">
            <div class="button-group2">
                <a class="submit" href={% url 'vote:index' %}>BACK</a>
            </div>
        </div>
        </form>
    </div>

{% endblock %}

templates/vote/user/cast_vote_auth.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Cast Vote Auth</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">

        <div class="content2">
            {% for message in messages %}
                <div class="message">
                    <h3>Error:</h3> {{ message }}
                </div>
            <br>
            {% endfor %}
        </div>

        <div class="title2">
            Cast Your Vote
        </div>

        <div class="content2">
            <div>
                Your Vote is your Future
            </div>
        </div>

        <div class="content2">
            <div>
                Please note that you can only vote once
            </div>
        </div>

        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="registration_number">Registration Number</label>
                        <input class="input" type="text" name="registration_number" maxlength="10" required="" id="registration_number">
                    </div>

                    <div class="button-group">
                        <a class="submit" href={% url 'vote:index' %}> BACK </a>
                        <input id="submit2" type="submit" value="NEXT"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/vote/user/check_details_auth.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Check Details Auth</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">

        <div class="content2">
            {% for message in messages %}
                <div class="message">
                    <h3>Error:</h3> {{ message }}
                </div>
            <br>
            {% endfor %}
        </div>

        <div class="title2">
            View Registration Details
        </div>

        <div class="content2">
            <div>
                To check your registration details, please input the following details
            </div>
        </div>

        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="registration_number">Registration Number</label>
                        <input class="input" type="text" name="registration_number" maxlength="10" required="" id="registration_number">
                    </div>

                    <div class="button-group">
                        <a class="submit" href={% url 'vote:index' %}> BACK </a>
                        <input id="submit2" type="submit" value="NEXT"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/vote/user/index.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Index</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        {% for message in messages %}
        <div class="message">
            <h3>Message :</h3> {{ message }}
        </div>
        {% endfor %}
        <div class="banner-container">
            <img class="banner" src="{% static 'images/Banner.svg' %}" alt="logo">
        </div>
        <div class="title">
            WELCOME!
        </div>

        <div class="content">
            Thank you for your interest in registering to vote. We are glad to be of assistance.
        </div>
        <div class="content">
            Please note that the voter registration application may be used to do the following:
        </div>
        <div class="list">
            <ul>
                <li>Register as a voter</li>
                <li>Check your voter registration status</li>
                <li>Update your registration information.</li>
                <li>Vote for your preferred candidate.</li>
            </ul>
        </div>
        <div class="content-title">
            To register, update or vote:
        </div>
        <div class="content">
            Use this website to submit an application online or cast a vote
        </div>
        <div class="content-title">
            To submit an online application, you will need:
        </div>
        <div class="list">
            <ul>
                <li>Valid School ID</li>
                <li>A recent digitized passport photo</li>
            </ul>
        </div>
        <div class="content-title">
            To be eligible to register to vote you must:
        </div>
        <div class="list-container">
            <div class="long-list">
                <ul>
                    <li>You must be a TUK Student.</li>
                    <li>You must be at least 18 years of age</li>
                    <li>You must not have been judged "mentally incompetent" in a court of law.</li>
                    <li>You must not have been convicted of an election offence during the preceding five years.</li>
                </ul>
            </div>
        </div>
        <div class="button-container">
            <a class="submit" href={% url 'vote:check_details_auth' %}>
                CHECK STATUS
            </a>
            <a class="submit2" href={% url 'vote:bio' %}>
                BEGIN REGISTRATION
            </a>
            <a class="submit2" href={% url 'vote:cast_vote_auth' %}>
                CAST VOTE
            </a>

            <a class="submit" href={% url 'vote:update_details_auth' %}>
                UPDATE DETAILS
            </a>
        </div>
    </div>

{% endblock %}

templates/vote/user/success.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Success</title>
{% endblock %}

{% block body_block %}
    <div class="parent">
        <div class="title">
            SUCCESS!
        </div>

        <div class="content">
            You have been successfully registered into the Voting Roll.
        </div>
        <div class="content">
            Good luck in the election
        </div>
        <div class="button-container">
            <a class="submit2" href="/vote">
                BACK TO HOME SCREEN
            </a>
        </div>
    </div>

{% endblock %}

templates/vote/user/user_account.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Authorization</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Your Account
        </div>

        <div class="formWrapper">
            <div class="form">

                <div class="fieldWrapper3">
                    <label for="id_ward_code">Username:</label>
                    <label for="id_ward_code">{{ uname }}</label>
                </div>

                <div class="fieldWrapper3">
                    <label for="id_ward_code">First Name:</label>
                    <label for="id_ward_code">{{ fname }}</label>
                </div>

                <div class="fieldWrapper3">
                    <label for="id_ward_code">Last Name:</label>
                    <label for="id_ward_code">{{ lname }}</label>
                </div>

                <div class="fieldWrapper3">
                    <label for="id_ward_code">Email Address:</label>
                    <label for="id_ward_code">{{ email }}</label>
                </div>

                     <div class="button-group">
                        <a id="submit2" href={% url 'vote:log_out' %}>LOGOUT</a>
                    </div>

            </div>
        </div>
    </div>
{% endblock %}